@startuml

skinparam groupinheritance 2

package fnifi {
    class FNIFI {
        -_conns : std::vector<IConnection*>
        -_colls : std::vector<Collection*>
        -_files : std::vector<File>
        -_sortingAlgo : sxeval::SXEval<expr_t>
        -_filteringAlgo : sxeval::SXEval<expr_t>
        -_sortedFiles : std::vector<File*>
        -_filteredFiles : std::vector<File*>
        -_sortFiltFiles : std::vector<File*>
        -_storingConn : IConnection*
        -_storingPath : std::string
        +FNIFI(conns : std::vector<IConnection*>&, colls : std::vector<Collection*>&,
        storingConn : IConnection*, storingPath : const char*)
        +index()
        +sort(exp : const char*)
        +filter(exp : const char*)
        +getFiles() : const std::vector<File*>&
        +begin() : const_iterator
        +end() : const_iterator
    }

    package file {
        enum MetadataType {
            +XMP
            +EXIF
            +IPTC
        }

        class File {
            -_id : const fileId_t
            -_coll : const Collection*
            +File(id : fileId_t, coll : const Collection*)
            +getId() : fileId_t
            +getPath() : std::string
            +getMetadata(os : std::ostream&, type : MetadataType,
            key : const char*) : std::ostream&
            +preview() : fileBuf_t
            +read() : fileBuf_t
        }

        class Collection {
            -_conn : IConnection*
            -_indexingPath : const std::string
            -_storingPath : const std::string
            -_nFiles : fileId_t
            -_offsets : std::fstream
            -_filepaths : std::fstream
            +Collection(conn : IConnection*, indexingPath : const char*,
            ~Collection()
            +index()
            storingPath : const char*)
            +getFirstId() : fileId_t
            +getLastId() : fileId_t
            +getFilePath(id : fileId_t) : std::string
            +preview(id : fileId_t) : fileBuf_t
            +read(id : fileId_t) : fileBuf_t
            -getPreviewFilePath(id : fileId_t) : std::string
        }
    }

    package connection {
        interface IConnection {
            +connect()
            +disconnect()
            +read(filepath : const char*) : fileBuf_t
            +write(filepath : const char*, buffer : const fileBuf_t&)
            +remove(filepath : const char*)
        }

        class SMB extends IConnection {
            +SMB(addr : const char*, user : const char*, pwd : const char*)
            +connect()
            +disconnect()
            +read(filepath : const char*) : fileBuf_t
            +write(filepath : const char*, buffer : const fileBuf_t&)
            +remove(filepath : const char*)
        }

        class Local extends IConnection {
            +Local()
            +connect()
            +disconnect()
            +read(filepath : const char*) : fileBuf_t
            +write(filepath : const char*, buffer : const fileBuf_t&)
            +remove(filepath : const char*)
        }
    }

    FNIFI o--> IConnection : 0..*\n_conns
    FNIFI o--> Collection : 0..*\n_colls
    FNIFI *--> File : 0..*\n_files
    FNIFI o--> File : 0..*\n_sortedFiles
    FNIFI o--> File : 0..*\n_filteredFiles
    FNIFI o--> File : 0..*\n_sortFiltFiles
    File o--> Collection : 1..1\n_coll
    Collection o--> IConnection : 1..1\n_conn
}

@enduml
